source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 2.0'

gem 'fix-db-schema-conflicts', path: '../..'
